package domain

import (
	"context"
	"time"

	"github.com/google/uuid"
)

// Attachment is a file in object storage that a ledger row, deposit
// deduction or owner statement points at. The bytes never pass through
// the API on upload: the client gets a presigned POST policy (which caps
// size and pins the content type at the storage layer), uploads straight
// to the bucket, then confirms — at which point the server checks the
// object really exists and only then marks it ready. Entities may only
// reference ready attachments the same owner owns.
type AttachmentStatus string

const (
	AttachmentStatusPending AttachmentStatus = "pending"
	AttachmentStatusReady   AttachmentStatus = "ready"
)

// MaxAttachmentBytes caps a single upload.
const MaxAttachmentBytes = 10 << 20

// AllowedAttachmentContentTypes is the upload allow-list: photos and PDFs.
var AllowedAttachmentContentTypes = map[string]string{
	"image/jpeg":      ".jpg",
	"image/png":       ".png",
	"image/webp":      ".webp",
	"application/pdf": ".pdf",
}

type Attachment struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	ObjectKey   string
	Filename    string
	ContentType string
	SizeBytes   int64
	Status      AttachmentStatus
	CreatedAt   time.Time
}

// PresignedUpload is what the client needs to upload directly to storage:
// POST multipart/form-data to URL with Fields first and the file last.
type PresignedUpload struct {
	Attachment *Attachment
	URL        string
	Fields     map[string]string
}

// FileStorage is the object-storage port. The S3 adapter lives in
// internal/infra/storage; NoopStorage stands in when none is configured.
type FileStorage interface {
	// PresignUpload returns a browser-usable POST target restricted to
	// exactly this key, content type and a 1..maxBytes size.
	PresignUpload(ctx context.Context, key, contentType string, maxBytes int64, ttl time.Duration) (url string, fields map[string]string, err error)
	PresignDownload(ctx context.Context, key, filename string, ttl time.Duration) (string, error)
	// Put stores server-generated content (statement PDFs).
	Put(ctx context.Context, key, contentType string, data []byte) error
	Get(ctx context.Context, key string) ([]byte, error)
	// Stat returns the stored object's size and content type, or ErrNotFound.
	Stat(ctx context.Context, key string) (size int64, contentType string, err error)
	Delete(ctx context.Context, key string) error
}

type AttachmentRepository interface {
	Create(ctx context.Context, a *Attachment) error
	GetByID(ctx context.Context, id uuid.UUID) (*Attachment, error)
	MarkReady(ctx context.Context, id uuid.UUID, sizeBytes int64) error
}

type AttachmentService interface {
	Presign(ctx context.Context, ownerID uuid.UUID, filename, contentType string, sizeBytes int64) (*PresignedUpload, error)
	Confirm(ctx context.Context, ownerID, id uuid.UUID) (*Attachment, error)
	DownloadURL(ctx context.Context, ownerID, id uuid.UUID) (url, filename string, err error)
	// Store saves server-generated bytes (e.g. an owner statement PDF) as
	// an already-ready attachment.
	Store(ctx context.Context, ownerID uuid.UUID, filename, contentType string, data []byte) (*Attachment, error)
	// Read returns an attachment's bytes (for emailing a PDF).
	Read(ctx context.Context, ownerID, id uuid.UUID) (*Attachment, []byte, error)
}
